-- =============================================================================
-- 2026-04-24  Card Batch Header/Detail Ledger
-- =============================================================================
-- Purpose:
--   Store processor close-batch results in first-class tables instead of JSON
--   snapshots inside transactions.message.
--
-- Tables:
--   public.card_batch_headers
--   public.card_batch_details
-- =============================================================================

create table if not exists public.card_batch_headers (
  id uuid primary key default gen_random_uuid(),
  batch_number bigint generated by default as identity,
  organization_id uuid not null,
  location_id uuid not null,
  terminal_id uuid,
  accepted boolean not null default false,
  processor_status text not null default '',
  processor_message text not null default '',
  terminal_name text not null default '',
  location_name text not null default '',
  organization_name text not null default '',
  organization_number text,
  closed_at timestamptz not null default timezone('utc', now()),
  transaction_count integer not null default 0,
  approved_count integer not null default 0,
  voided_count integer not null default 0,
  original_total numeric(12,2) not null default 0,
  tip_total numeric(12,2) not null default 0,
  final_total numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  integrity_status text not null default '',
  integrity_summary text not null default '',
  processor_close_raw text,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_card_batch_headers_batch_number
  on public.card_batch_headers (batch_number);

create index if not exists idx_card_batch_headers_org_loc_closed
  on public.card_batch_headers (organization_id, location_id, closed_at desc);

create index if not exists idx_card_batch_headers_terminal_closed
  on public.card_batch_headers (terminal_id, closed_at desc)
  where terminal_id is not null;

-- Optional FK if terminals table exists and terminal_id is used.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'card_batch_headers_terminal_id_fkey'
  ) then
    alter table public.card_batch_headers
      add constraint card_batch_headers_terminal_id_fkey
      foreign key (terminal_id)
      references public.terminals (id)
      on delete set null;
  end if;
end $$;

create table if not exists public.card_batch_details (
  id uuid primary key default gen_random_uuid(),
  card_batch_header_id uuid not null
    references public.card_batch_headers (id) on delete cascade,
  organization_id uuid not null,
  location_id uuid not null,
  transaction_detail_id uuid,
  transaction_header_id uuid,
  reference_id text,
  amount numeric(12,2) not null default 0,
  card_type text,
  card_last4 text,
  auth_code text,
  status text not null default '',
  close_status text not null default '',
  integrity_status text not null default '',
  integrity_summary text not null default '',
  processor_reference_id text,
  processor_transaction_type text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.card_batch_headers
  add column if not exists integrity_status text not null default '';

alter table public.card_batch_headers
  add column if not exists integrity_summary text not null default '';

alter table public.card_batch_headers
  add column if not exists processor_close_raw text;

alter table public.card_batch_headers
  add column if not exists original_total numeric(12,2) not null default 0;

alter table public.card_batch_headers
  add column if not exists tip_total numeric(12,2) not null default 0;

alter table public.card_batch_headers
  add column if not exists final_total numeric(12,2) not null default 0;

alter table public.card_batch_details
  add column if not exists integrity_status text not null default '';

alter table public.card_batch_details
  add column if not exists integrity_summary text not null default '';

alter table public.card_batch_details
  add column if not exists processor_reference_id text;

alter table public.card_batch_details
  add column if not exists processor_transaction_type text;

create index if not exists idx_card_batch_details_header
  on public.card_batch_details (card_batch_header_id);

create index if not exists idx_card_batch_details_org_loc_created
  on public.card_batch_details (organization_id, location_id, created_at desc);

create index if not exists idx_card_batch_details_txn_detail
  on public.card_batch_details (transaction_detail_id)
  where transaction_detail_id is not null;

create index if not exists idx_card_batch_details_reference
  on public.card_batch_details (reference_id)
  where reference_id is not null;

-- RLS ------------------------------------------------------------------------
alter table public.card_batch_headers enable row level security;
alter table public.card_batch_details enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.card_batch_headers to anon, authenticated;
grant select, insert on table public.card_batch_details to anon, authenticated;

-- Read policies
drop policy if exists "CardBatchHeaders read authenticated" on public.card_batch_headers;
create policy "CardBatchHeaders read authenticated"
  on public.card_batch_headers
  for select
  to authenticated
  using (
    exists (
      select 1 from public.user_memberships m
      where m.user_id = auth.uid()
        and m.organization_id = card_batch_headers.organization_id
        and (m.location_id is null or m.location_id = card_batch_headers.location_id)
    )
  );

drop policy if exists "CardBatchHeaders read anon" on public.card_batch_headers;
create policy "CardBatchHeaders read anon"
  on public.card_batch_headers
  for select
  to anon
  using (
    public.is_valid_location_scope(card_batch_headers.organization_id, card_batch_headers.location_id)
  );

drop policy if exists "CardBatchDetails read authenticated" on public.card_batch_details;
create policy "CardBatchDetails read authenticated"
  on public.card_batch_details
  for select
  to authenticated
  using (
    exists (
      select 1 from public.user_memberships m
      where m.user_id = auth.uid()
        and m.organization_id = card_batch_details.organization_id
        and (m.location_id is null or m.location_id = card_batch_details.location_id)
    )
  );

drop policy if exists "CardBatchDetails read anon" on public.card_batch_details;
create policy "CardBatchDetails read anon"
  on public.card_batch_details
  for select
  to anon
  using (
    public.is_valid_location_scope(card_batch_details.organization_id, card_batch_details.location_id)
  );

-- Insert policies
drop policy if exists "CardBatchHeaders insert authenticated" on public.card_batch_headers;
create policy "CardBatchHeaders insert authenticated"
  on public.card_batch_headers
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.user_memberships m
      where m.user_id = auth.uid()
        and m.organization_id = card_batch_headers.organization_id
        and (m.location_id is null or m.location_id = card_batch_headers.location_id)
    )
  );

drop policy if exists "CardBatchHeaders insert anon" on public.card_batch_headers;
create policy "CardBatchHeaders insert anon"
  on public.card_batch_headers
  for insert
  to anon
  with check (
    public.is_valid_location_scope(card_batch_headers.organization_id, card_batch_headers.location_id)
  );

drop policy if exists "CardBatchDetails insert authenticated" on public.card_batch_details;
create policy "CardBatchDetails insert authenticated"
  on public.card_batch_details
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.user_memberships m
      where m.user_id = auth.uid()
        and m.organization_id = card_batch_details.organization_id
        and (m.location_id is null or m.location_id = card_batch_details.location_id)
    )
  );

drop policy if exists "CardBatchDetails insert anon" on public.card_batch_details;
create policy "CardBatchDetails insert anon"
  on public.card_batch_details
  for insert
  to anon
  with check (
    public.is_valid_location_scope(card_batch_details.organization_id, card_batch_details.location_id)
  );
