-- ============================================================
-- Terminal URL Token Identity System
-- 2026-04-18
--
-- Adds a terminal_token column (unique, opaque UUID) to terminals.
-- Tokens are generated by the server-side RPC below and stored in
-- Supabase. The web app receives its token via the ?tk= URL param.
-- Anon callers can resolve their full terminal context with the
-- token but cannot enumerate or look up other terminals.
-- ============================================================

-- 1. Add terminal_token column (idempotent)
alter table public.terminals
  add column if not exists terminal_token text;

create unique index if not exists idx_terminals_token
  on public.terminals (terminal_token)
  where terminal_token is not null;

-- 2. RPC: resolve_terminal_from_token
--    Returns the full terminal context needed by StartupScreen.
--    Anon-callable. Returns 0 rows if token is not found/inactive.

create or replace function public.resolve_terminal_from_token(p_token text)
returns table (
  terminal_id       uuid,
  terminal_number   text,
  terminal_name     text,
  location_id       uuid,
  location_name     text,
  organization_id   uuid,
  organization_number text,
  organization_name text,
  license_key       text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Reject empty/null tokens immediately
  if p_token is null or trim(p_token) = '' then
    return;
  end if;

  return query
    select
      t.id                                       as terminal_id,
      t.terminal_number                          as terminal_number,
      coalesce(t.terminal_name, 'Terminal ' || t.terminal_number) as terminal_name,
      t.location_id                              as location_id,
      coalesce(l.name, '')                       as location_name,
      t.organization_id                          as organization_id,
      coalesce(o.organization_number, '')        as organization_number,
      coalesce(o.name, '')                       as organization_name,
      coalesce(o.license_key, '')                as license_key
    from public.terminals t
    left join public.locations  l on l.id = t.location_id
    left join public.organizations o on o.id = t.organization_id
    where t.terminal_token = trim(p_token)
      and t.is_active = true
    limit 1;
end;
$$;

-- Grant anon execution rights
grant execute on function public.resolve_terminal_from_token(text) to anon;

-- 3. RPC: generate_terminal_token
--    Generates and stores a fresh token for a given terminal.
--    Intended for admin/service-role use when provisioning terminals.
--    Anon callers cannot call this (no grant to anon).

create or replace function public.generate_terminal_token(p_terminal_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
begin
  v_token := gen_random_uuid()::text;

  update public.terminals
  set terminal_token = v_token
  where id = p_terminal_id;

  if not found then
    raise exception 'Terminal % not found', p_terminal_id;
  end if;

  return v_token;
end;
$$;

-- Note: do NOT grant anon access to generate_terminal_token.
-- Only authenticated admins / service role should call it.

comment on column public.terminals.terminal_token is
  'Opaque URL token used for web-based terminal identity (?tk=<token>). '
  'Generated server-side via generate_terminal_token(). '
  'Never expose in client-side enumeration queries.';
