-- Removes legacy processor credential/config columns from locations,
-- including retired legacy gateway location fields.
-- Safe to run multiple times.
--
-- IMPORTANT:
-- - This intentionally does NOT drop core address/contact/location fields.
-- - Keep terminal-level SPIn fields on public.terminals.

begin;

-- Optional safety archive for legacy location credentials prior to drop.
create table if not exists public.locations_legacy_processor_archive (
  id bigint generated by default as identity primary key,
  location_id uuid,
  organization_id uuid,
  legacy_gateway_api_login_id text,
  legacy_gateway_transaction_key text,
  processor_provider text,
  processor_environment text,
  processor_mode text,
  payment_processor text,
  gateway_environment text,
  epn_api_login_id text,
  epn_login_id text,
  epn_user_id text,
  epn_userid text,
  epn_password text,
  epn_pass text,
  epn_restrict_key text,
  epn_restriction_key text,
  archived_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.locations_legacy_processor_archive
  add column if not exists location_id uuid,
  add column if not exists organization_id uuid,
  add column if not exists legacy_gateway_api_login_id text,
  add column if not exists legacy_gateway_transaction_key text,
  add column if not exists processor_provider text,
  add column if not exists processor_environment text,
  add column if not exists processor_mode text,
  add column if not exists payment_processor text,
  add column if not exists gateway_environment text,
  add column if not exists epn_api_login_id text,
  add column if not exists epn_login_id text,
  add column if not exists epn_user_id text,
  add column if not exists epn_userid text,
  add column if not exists epn_password text,
  add column if not exists epn_pass text,
  add column if not exists epn_restrict_key text,
  add column if not exists epn_restriction_key text,
  add column if not exists archived_at timestamptz not null default timezone('utc', now());

insert into public.locations_legacy_processor_archive (
  location_id,
  organization_id,
  legacy_gateway_api_login_id,
  legacy_gateway_transaction_key,
  processor_provider,
  processor_environment,
  processor_mode,
  payment_processor,
  gateway_environment,
  epn_api_login_id,
  epn_login_id,
  epn_user_id,
  epn_userid,
  epn_password,
  epn_pass,
  epn_restrict_key,
  epn_restriction_key
)
select
  l.id,
  l.organization_id,
  nullif(trim(coalesce(to_jsonb(l)->>'legacy_gateway_api_login_id', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'legacy_gateway_transaction_key', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'processor_provider', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'processor_environment', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'processor_mode', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'payment_processor', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'gateway_environment', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_api_login_id', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_login_id', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_user_id', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_userid', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_password', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_pass', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_restrict_key', '')), ''),
  nullif(trim(coalesce(to_jsonb(l)->>'epn_restriction_key', '')), '')
from public.locations l;

-- Reset terminal activation state for clean re-activation flow.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'terminals'
      and column_name = 'is_active'
  ) then
    update public.terminals
    set is_active = false,
        registered_device_id = null,
        registered_device_label = null
    where coalesce(is_active, true) = true
       or registered_device_id is not null
       or registered_device_label is not null;
  end if;
end;
$$;

update public.locations
set terminals_active = 0
where coalesce(terminals_active, 0) <> 0;

alter table public.locations
  drop column if exists legacy_gateway_api_login_id,
  drop column if exists legacy_gateway_transaction_key,
  drop column if exists processor_provider,
  drop column if exists processor_environment,
  drop column if exists processor_mode,
  drop column if exists payment_processor,
  drop column if exists gateway_environment,
  drop column if exists epn_api_login_id,
  drop column if exists epn_login_id,
  drop column if exists epn_user_id,
  drop column if exists epn_userid,
  drop column if exists epn_password,
  drop column if exists epn_pass,
  drop column if exists epn_restrict_key,
  drop column if exists epn_restriction_key;

commit;
